name: tg-blog-updater

services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile
    image: hatamiarash7/tg-blog-updater:latest
    env_file:
      - .env
    restart: unless-stopped
    init: true
    stop_grace_period: 15s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
