version: "3.9"
name: tg-blog-updaater
services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - tg-blog-updater:*
      target: builder
    command:
      - python
      - -m
      - tg_blog_updater
    image: hatamiarash7/tg-blog-updater:v1.0.0
    env_file:
      - .env
