version: "3.9"
name: tg-blog-updaater
services:
  updater:
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - tg-blog-updater:*
      target: builder
    image: hatamiarash7/tg-blog-updater:latest
    env_file:
      - .env
